# Archivo de configuración de Spring Boot
# Define el puerto y la configuración de RabbitMQ
server:
  port: 8080
spring:
  application:
    name: fleet-api
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin123}
